[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "npm"
version_scheme = "semver"
tag_format = "v$version"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
  'README.md:^\*\*Version\*\*: (?P<version>.*)'
]
